backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: images
collections:
  - name: "documentation"
    label: "Documentation"
    folder: "content/en/docs"
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Lead", name: "lead", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "toc", name: "toc", widget: "boolean", default: true, required: false }
      - label: "Menu"
        name: menu
        widget: object
        fields:
        - label: "Docs"
          name: docs
          widget: object
          fields:
            - {label: "Parent", name: parent, widget: string,  default: "prologue" }
    meta: { path: { widget: string, label: 'Path' } }



     