[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[main]]
  name = "Docs"
  url = "/docs/prologue/introduction/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 10


# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
